arb-dir: lib/src/common/localization/l10n/
template-arb-file: app_en.arb
output-class: AppLocalizations
output-dir: lib/src/common/localization/generated/
output-localization-file: app_localizations.dart
untranslated-messages-file: lib/src/common/localization/untranslated.txt